blank_issues_enabled: false
contact_links:
  - name: ❔ Question or ✨ Feature Request
    url: https://github.com/nshenderov/strapi-plugin-ckeditor/discussions
    about: Please use GitHub discussions for questions and feature requests